# Generated by Django 2.2.1 on 2019-05-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_auto_20190522_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='user_profile',
        ),
    ]
