# Generated by Django 2.2.1 on 2019-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0003_auto_20190522_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
    ]
