# Generated by Django 2.2.1 on 2019-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0006_auto_20190522_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
