# Generated by Django 2.2.1 on 2019-05-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
    ]
