# Generated by Django 2.2.1 on 2019-05-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0009_remove_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
