# Generated by Django 2.2.1 on 2019-05-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0010_userprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='prof_image',
        ),
    ]
